### PR TITLE
Fix error in translation

### PR DESCRIPTION
**Pull request by marie090101**
Fixed error in translation and made sentences easy-comprehensible.

In addition, missing Italic syntax in [previous merged commit](09248989b870ea8c21338518cffce8a185a78059) is fixed in this PR.

### CODE REVIEW

**Comment by oppai** [comment]
:+1:

**Comment by jarinosuke** [comment]
@marilla716 thanks! (and sorry to be late)
there's a lot of lost in translation

@marilla716 could you merge latest master before merging this PR?
thanks for your contribution!

**Comment by marie090101** [comment]
@jarinosuke 
I merged the latest master of your master into this branch.
Would you review this PR again?

**Comment by jarinosuke** [comment]
@marilla716 Thank you very much!

**Pull request merged**
